# Generated by Django 4.2.7 on 2023-12-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePic',
            field=models.ImageField(default='profile_images/default_profile_image.png', upload_to='profile_images/'),
        ),
    ]
